### PR TITLE
Updates to Journalist can Add Image

### PR DESCRIPTION
**Pull request by kaylawoodbury**
# [PT Story](https://www.pivotaltracker.com/story/show/171832479)
## User Story
```
As a journalist 
In order to make my articles more visually appealing 
I would like to be able to upload and display images to my articles
```
## Changes proposed in this pull request:
* Update typo in the decode_service file
* Add content to article serializer to send off image back to the front end

## What I have learned working on this feature:
* How to send images to the front end

## Gems Added
- gem 'aws-sdk-s3

### CODE REVIEW

**Review by pierre-1 — COMMENTED** [review]
LGTM. We will just have to monitor the coverage going forward.

**Comment by ghost** [comment]
Looks good!

**Review by robin-lillqvist — APPROVED** [review]
LGTM

**Comment by robin-lillqvist** [comment]
Merged

**Pull request merged**
